= Eclipse : Les raccourcis claviers utiles
:hp-tags: eclipse,IDE,raccourcis clavier
:published_at: 2013-02-23

Allez hop go, on se lance dans le premier article sur la prise en main d’Eclipse. Enfin plutôt sur l’amélioration de ma productivité via l’utilisation d’Eclipse. Cet article est le premier de la série sur mon apprentissage de mon IDE préféré. Non je ne trolle pas, c’est bien mon IDE préféré. J’avoue ne pas en avoir testé des milliers mais, je préfère Eclipse à Netbeans (surement parce que je le connais mieux en fait). Les goûts ça ne se commande pas.

Dans cet article, je vais présenter les raccourcis claviers que j’apprécie pour travailler plus vite et mieux. J’en connaissais certains depuis longtemps, d’autres m’ont été présentés par un nouveau collègue et d’autres, j’ai fouillé un peu dans Eclipse pour les découvrir. Ce n’est pas du tout une liste exhaustive des raccourcis qui existent. Il y en a beaucoup et on peut facilement en créer d’autres.

* *ctrl + shift + L* : raccourci affichant la liste des raccourcis. Je le met en premier car finalement c’est le plus important pour s’améliorer. Un second appuis ouvre la fenêtre d’édition des raccourcis
* *ctrl + espace* : en toute logique, ça vous connaissez déjà. Il permet l’autocomplétion lorsque l’on écrit notre code. Oui mais il ne fait pas qu’une simple autocomplétion sur le nom d’une méthode, d’un attribut ou d’une variable. Ce raccourci clavier a un comportement adapté au context dans lequel on travaille. Par exemple, si l’on est entrain d’écrire un nom, ctrl + espace nous montrera la liste des élements dont le nom correspond. Dans le cas où l’on est en dehors d’une méthode et que l’on commence à taper le nom d’une méthode, le raccourci propose les méthode dont le nom correspond. Là vous allez me dire que c’est pareil. Oui mais suivi d’un appuie sur entrée, on obtient une surcharge de la dite méthode. Je vous conseille d’apprendre à vous en servir au maximum (moi j’ai encore du boulot sur ce côté là).
* *ctrl + 1* : le quick fix. Sur un clavier US c’est juste ctrl + 1, sur un clavier azerty, il faut bien penser à faire *ctrl + shift + touche 1/&*. Lorsque l’on est sur une erreur, un warning, on a la solution de bouger la souris pour voir afficher une pop-up d’aide. Ce raccourci vous permet de l’afficher directement. Ensuite plus qu’à jouer avec les flèches pour sélectionner la solution que vous voulez.
* *ctrl + shift + R* : Affiche la fenêtre d’ouverture de ressources (fichiers). Ecrire dans la partie filtre pour retrouver rapidement l’élément que l’on souhaite et sélectionner le fichier pour directement ouvrir l’éditeur associé. Le nom écrit peut utiliser le caractère *** pour éviter de tout écrire entre 2 lettres que vous connaissez. Personnellement j’adore ce raccourci. Pour information dans le cas de classes Java, vous pouvez directement taper que les lettres majuscules dans la partie filtre. C’est beaucoup plus rapide. Par exemple : taper MC pour MaClasse.
* *ctrl + shift + T* : Affiche la fenêtre d’ouverture de classes. C’est un plus ou moins la même fenêtre que précédemment mais focalisé sur les classes. Il y a par contre toutes les classes disponibles telles que celles des bibliothèques/frameworks que vous utilisez.
* *ctrl + O* : Lorsque l’on est dans une classe, ce raccourci propose la liste des méthode et attributs de la classe. Tout comme pour les raccoucis précédents, vous pouvez filtrer les données affichées en tapant le début du nom de l’élément auquel vous souhaitez accéder.
* *ctrl + shift + O* : permet d’organiser les imports (ajouter ceux qui manquent et supprimer ceux qui sont inutiles)
* *ctrl + T* : ouvre la hiérarchie d’un type. Ceci permet sur une classe/interface d’afficher en pop-up les classes mères et filles. Utile notamment si l’on fait passer d’une interface à l’une des implémentations
* *ctrl + shift + /* ou *ctrl + shift + c* : petite préférence pour le second. Permet de commenter/décommenter du code. Sse raccourci s’adapte au type de fichier en cours d’édition notamment si l’on édite du JS, du html ou des tags dans les .jsp/.jspx
* *alt + shift + R* : permet de renommer. Fonctionne sur les variables, les méthodes mais également sur les classes/interfaces en renommant le fichier. Ce raccourci met également à jour les références de l’élément renommé. Peut parfois générer des erreurs si certaines références ne peuvent pas être mises à jour. Prend en compte également les références dans la javadoc
* *alt + shift + S* : affiche le menu « source » (celui que l’on obtient par clic droit > source). Nettement plus rapide pour ce qui est lié à la génération de code, de commentaires… Je l’apprécie générallement dans la création de mes JavaBeans
* *alt + shift + Z* : affiche un menu proposant d’encapsuler le code sélectionné. Permet d’encapsuler rapidement dans des if, des boucles ou des try/catch du code existant
* *alt + shift + M* : extrait le code sélectionné dans une méthode privé. Super pratique lors du refactoring du code. Ne pas hésiter à en abuser notamment lors d’évolution rendant le code illisible
* *ctrl + L* : accède à la ligne indiqué
* *ctrl + D* : supprime la ligne sur laquelle on est. Plus rapide que de la sélectionner et de la supprimer (je dis ça mais les habitudes ont la vie dure)
* *ctrl + F11* : le petit (gros ?) plus que j’ai appris récemment (enfin que je retiens maintenant). Rejoue la dernière Run Configuration lancé. Super pratique dans le cas du TDD ou simplement de la correction/mise en place de TU

Bien entendu, la liste de ces raccourcis n’est pas exhaustive. Loin de là en fait. Par contre c’est ceux que j’utilise le plus et auquels je pense. N’hésitez pas à m’indiquer ceux que vous utilisez de votre côté, je les rajouterais.