= Problème de background dans le thème Dark d’Eclipse
:published_at: 2014-07-25
:hp-tags: eclipse



Je ne sais pas si vous aviez lu mon article précédent, mais j’abordais rapidement le fait qu’un thème « Dark » soit nativement présent dans Eclipse depuis la version Luna. J’avais fait mention d’un petit souci de couleur de fond des éditeurs dans certains packagings et je souhaitais vous donner une solution de contournement. En fait, il y a mieux.

Plusieurs bugs ont été créés sur le tracker d’Eclipse. (link:http://eclip.se/438475[bug 438475] et link:http://eclip.se/438175[bug 438175]). Ces bugs sont maintenant résolus et au lieu d’un contournement qui aurait supprimé une partie des fonctionnalités des packagings Eclipse concerné, on peut simplement mettre à jour le composant fautif.

== Solution

Pour installer la correction, lancer Eclipse et accéder à l’installation de nouveaux plugins (Help > Install New Software…). Saisir l’url suivante : http://download.eclipse.org/tm/updates/3.6milestones/20140704.

Pour récupérer uniquement la correction, décocher l’option « Group Items by Category » et sélectionner le plugin nommé « Target management Terminal Widget ». Poursuivez l’installation de ce composant et redémarrer Eclipse. Il ne devrait plus y avoir de problème de background.
