= Web開発って結局どうなの？
:hp-alt-title: web-develop
:hp-tags: blog,web
:published_at: 2015-08-01

そもそも自分がプログラミングを始めたきっかけがVBScript(Visual Basic Scripting Editon)と呼ばれるWindows Script Hostに搭載しているVisual Basic 6.0のサブセット版なので、そもそもWebアプリの開発というのがよくわかりません。現在は一応Web開発のためにPHPやらJavaScriptの勉強をしていますが・・・・・・。

そもそもWebアプリの利点をまとめると

* 基本的にどんなプラットホームでも動く
* インストールが不要
* 開発が比較的手軽
* バージョンアップも容易

なんだと思います。自分自身、現在はWindowsも使っていますが基本的にLinuxでの開発がメインになっている以上クロスプラットホームアプリケーションの開発という義務のようなものがあるんじゃないかと感じています。

日本でもWindowsXPサポート終了の影響でLinux使用者が多くなってきました。しかし、使いたいソフトが無かったり操作性が慣れなかったりと、結局お金がかかってもWindowsやMacのほうが楽だしLinuxを使う意味はないということになります。しかしWebサービスだったら操作性はほとんど変わらないのでネット専用で使う人も多いと聞きます。

その他にも最近はLinux搭載の低価格ノートパソコン「Chrome Book」というのが発売しています。基本的にGggole Chromeしか使えないことによってOS費を抑えて結果的に消費者が安く買えるという画期的なものです。Linux標準のパソコンとしてはUbuntuなどと比べ物にならないくらい解説書を書店で見かけます。そしてその解説書に共通して書いてあることとして、そのパソコンに搭載されているOS「Chrome OS」の最大の特徴がネットしか使えないことと書いてあります。

以上のように最近はデスクトップアプリケーションを使わずにWebアプリケーションだけで何でも済ませる人が増えています。TwitterやFaceBookは定番ですが、画像編集で「Pixlr Edit」だったりデスクトップもブラウザで再現する「Zero PC」などもあります。そう考えるとProjectTMWでもWebアプリの開発が必須になると思うのです。

しかし、今までデスクトップアプリケーションを開発してきた身としては結構感覚が違うんでどうなのかなぁと考えてしまうのが現状だったりもします。そもそもサーバーで動作させるので前提が違うという。まあどちにしろプログラミング言語と捉えれば全部同じじゃんと行ってしまえば終わりなんですが・・・・・。まあ考える必要があるのかな。
