= Eclipse Mars - épisode 3 - Amélioration de l'ergonomie de la console
:hp-tags: eclipse, mars

A part au niveau des éditeurs de code, un développeur passe un peu de temps dans la console pour voir comment son programme se comporte. Que ce soit pour simplement vérifier le fonctionnement général de l'application ou bien pour vérifier qu'il n'y a pas d'exceptions générées lors de l'utilisation de l'application.

Eclipse Mars (qui sort en juin) comporte donc quelques améliorations pour nous développeurs. Je les trouve plutôt sympathique donc autant vous en faire profiter.

== Vérouillage automatique du défilement

Un truc assez embêtant lorsque les logs de l'application sont verbeux, c'est que l'on a généralement pas le temps de lire les logs que d'autres sont de nouveaux écrits dans la console. Ce qui empêche le développeur que je suis de finir de lire ce que j'avais commencé. 

Généralement, l'utilisateur va donc remonter avec dans les logs avec la barre de défilement. Malheureusement cela ne résout pas le problème puisqu'à chaque nouvelle ligne de log, la console réaffiche les lignes nouvellement écrites.

Pour désactiver ce fonctionnement et permettre la lecture des logs, il existe un bouton permettant de bloquer le défilement. Il n'est pas activé par défaut (à mon avis heureusement) mais peut être utile de temps à autres.