= Django MongoDB Engine
:hp-tags: python,mongo,django

:numbered:

== Installation

Django MongoDB Engine depends on

* link:http://django-nonrel.org/[Django-nonrel], a fork of Django that adds support for non-relational databases.
* link:https://github.com/django-nonrel/djangotoolbox[djangotoolbox], a bunch of utilities for non-relational Django applications and backends.

It’s highly recommended (although not required) to use a link:http://www.virtualenv.org/[virtualenv] for your project to not mess up other Django setups.

=== virtualenv

If not already installed, grab a copy from the Cheeseshop:

[source,bash]
----
pip install virtualenv
----

To set up a virtual environment for your project, use

[source,bash]
----
virtualenv myproject
----

To join the environment, use (in Bash):

[source,bash]
----
source myproject/bin/activate
----

=== Django-nonrel
Django fork with support for NoSQL databases

[source,bash]
----
pip install git+https://github.com/django-nonrel/django@nonrel-1.7
----

=== djangotoolbox

Djangotoolbox provides a common API for running Django on non-relational/NoSQL databases.

[source,bash]
----
pip install git+https://github.com/django-nonrel/djangotoolbox
----

=== Django MongoDB Engine

You should use the latest Git revision.

[source,bash]
----
pip install git+https://github.com/django-nonrel/mongodb-engine
----

== Configuration

Database setup is easy (see also the link:https://docs.djangoproject.com/en/dev/ref/settings/#databases[Django database setup docs]):

[source,python]
----
DATABASES = {
   'default' : {
      'ENGINE' : 'django_mongodb_engine',
      'NAME' : 'my_database'
   }
}
----

Django MongoDB Engine also takes into account the HOST, PORT, USER, PASSWORD and OPTIONS settings.

Possible values of OPTIONS are described in the link:https://django-mongodb-engine.readthedocs.org/en/latest/reference/settings.html[settings reference].

== First tutorial
