= Virtual Trials

Not so long ago, a story went viral on social media about a woman being molested at a crowded traffic signal in potentially the most dangerous place in India, its capital.
The woman posted pictures of her molester online along with her version of how the story unfolded. 
The story went viral instantly and all major publication houses picked it up.
People across the country expressed their views on this particular story and a large majority of these people went ahead and declared the accused to be guilty without even examining his side of the incident.
Leading news channels such as Times Now held prime time debates on the issue and even had the so-called victim on their panel. The Chief Minister of Delhi showed his support for the victim through his tweets and encouraged more women to follow in her footsteps. 

All the meanwhile, I kept wondering how the mainstream media and country’s so-called leading politicians could be so naive. Though as citizens of India, we should take full responsibility for the CM’s rapid response to this story, after all we chose such an able representative. Could they *be* any more gullible? (Just couldn’t help the Chandler Bing reference)

===== Why was there no mention of the other side of the story?

I am all for women’s rights and equality but aren’t we being unfair to the accused? This particular incident shows how it has become so easy for a woman to thrash a man’s reputation to the ground.  Just by posting a few pictures along with a caption, the person is sentenced guilty by the online court without giving him an opportunity to defend himself. That’s how vulnerable men are nowadays.

The kind of world we’re living in today, a man is guilty until proven innocent. 

====== Harshvardhan Kuthal
