= Budapest JS 2016 - Part I: the workshop about Haxe

I attended for first time the JS conference celebrated in the capital city of Hungary. In this post I want to share a few notes from my experience there, first from the workshop, then from the talks per se.

The title of the workshop I did was:

== Developing applications using the Haxe language

I planned to go to a hardware related workshop, but I had to attend the one related to the http://haxe.org/[Haxe Language] in a company that really uses it for production. It was very interesting as it seems the true inheritor of *Flash*, and is somehow used in the adult content industry. Yes, you have read the last sentence correctly. They were also recruiting, btw.

The Haxe language is very interesting for several reasons: it has survived for more than ten years in the industry (wow!), is able to target several platforms and it has evolved slowly but steadily in its lifetime. For people who doesn't know the language, it is a strongly typed language with C syntax, much on the Java/Go way. It uses a classical object oriented scheme and has its own standard library, that is very complete. I would say it's really a transpiler, before CoffeeScript started the trend in the JS world. It doesn't have its own VM, so it's not tied to any platform. It targets several platforms, from PHP to Javascript and Python, in different OS, and does it in a clean way. This approach makes you think a lot about languages being only gateways to their underlying platforms, something that we usually forget when we developers decide the tools we are going to use for a new project or problem.

I knew the language from a few games that where ported to Android and web a few years ago, and back then I remember I was very surprised with the solidity of the products, in contrast with all the glitches and problems of first HTML5 games of those years. The small job market disregarded the language for many people that looked for a better chance of finding a job in the industry, but it seems that many freelancers took serious advantage of it.

The guys doing the workshop/conference were really patient doing the explanations, as the attendance were mostly eskeptical. They had a lot of experience and they were interested in looking for a tool that solved the problem of long-time application maintenance. As they were not satisfied with Javascript, they tried the very promising Typescript language. And it seems the Microsoft language still has a lot of drawbacks when dealing with transpiling to real JS. They needed something better, so they tried Haxe and  fell in love inmediately with it as things were really smooth from the very first moment.

A counterpoint to this approach is that Javascript itself has it's own standard, ECMAScript, that is in very good health even after years of discussions and fights over corporate interests. So in these days, makes sense to use Javascript for everything and disregard other options. In any case, the Haxe compilation to Javascript is not very arcane, so it would be possible to reuse the compiled code is someone that uses the old platform decides to disregard it.

Haxe has been there since 2004, and since them there have been a lot of trends. From the absolute kingdom of Flash for web games and presentations, to the rise of Javascript with Ajax, the fall of Java in web and the declining of PHP. As Haxe is an independent language, driven by its own independent foundation and not a big corporation, like Python, that makes people more confident on its future, as is less probable that their maintainers simply drop it. In this industry, even successful languages like Java, have to struggle with their corporate owners. It's worth to mention that contributions are welcome.

== Organization

The organizers should improve the workshops assignation, as people should be able to choose them. A lot of people were interested in the hardware related stuff, it seems the hot stuff right now. The angular2 was also very popular, as a lot of people will need to migrate their apps to the new version. As the version 2 uses Typescript, the controversy has already arisen.

Anyway, the workshops were included in the conference price, so it was a good deal. Kudos for the organizers, as not all the confs have this kind of bonus.

== The city

On a side related note, the city is really interesting, with lots of history and nigthlife. And many dark sides. Worths a visit without any doubt.

See you for the second part, about the talks themselves.

