= イノベーションエンジニアブログはじめました
:hp-alt-title: FirstPost
:hp-tags: FirstPost,YAGASAKI,COBOL,ZUNDOKO

はじめまして！

株式会社イノベーションの矢ヶ崎と申します。

弊社でも、とうとうエンジニアブログをはじめました！

いままで、弊社ではエンジニア自体が少なく、少ない個々のエンジニアがプロダクトを必死になって作るというカタチでした。
しかし！技術的にやりたいことがドンドン増えて行き、そしてエンジニアの人数もちょっとづつ増え、晴れてこの４月からエンジニアの組織というものが出来ました！これからは、個々ではなくチームでガンガン開発・運用などなどしていきます！

そこで、エンジニアがエンジニアであり続けるため、また社外のエンジニアの方々に、株式会社イノベーションっていう会社は何をやっている(創っている)会社なのかを少しでもわかっていただけるように、エンジニアブログをはじめさせていただきたいと存じます。
初回は、僭越ながら言い出しっぺの矢ヶ崎がキーボードを取らせていただきます。

ふつー初回のブログでは、弊社の紹介とか、自己紹介とか、使っている言語・フレームワーク、開発ツールなどなどを書くのかもしれませんが、他の方がきっと書いてくれると信じていますので、あえて最近流行っている「ズンドコキヨシ」のネタを書いてみたいと思います。

## 「ズンドコキヨシ」とは

いま、「ズンドコキヨシ」が熱いです。
「ズン」と「ドコ」をランダムに表示し、例の歌詞っぽい状態になったら、「キ・ヨ・シ！」と表示させる関数を作るという、とっても素敵な発想をした方がいらっしゃったのが元とのことです。

以下、Qiitaでまとめていただいている方がいらっしゃるので、URL記載しておきます！
http://qiita.com/shunsugai@github/items/971a15461de29563bf90

## COBOLでズンドコ

個人的に、Qiitaの方にも書かせていただいた内容なのですが、自社のブログではもう少し詳しく書きたいと思います。
20年ぶりくらいにCOBOLを書いたのですが、やはりこの言語は非常にわかりやすく、新人エンジニアが、コンピュータのことを学ぶのにはとても良い言語だと思いました。構造体・共用体がわからない方や、基本的なアルゴリズムの勉強をしたい方は、C言語で学ぶよりスッと入ってくると思いますので、おすすめです！
とはいえ、このWeb時代にCOBOLばっかりやっているのもしんどいと思いますので、JavascriptとCOBOLを同時に初めてみるのはいかがでしょうか？
PCでCOBOL書くのは、想像以上に書きづらいとしても！

ちなみに、好きな言語はGoとC++です。

## 準備

今回は、GnuCOBOL (formerly OpenCOBOL)っていうのを使わせていただきました。
Macだったら、

```shell-session
$ brew install open-cobol
```
であっさり入ります。

## 中身

ソースコードはこんな感じにしてみました。
行番号も含めて丸ごとソースコードですのでお気をつけください。

```cobol:zd.cob
000010 IDENTIFICATION DIVISION.
000020 PROGRAM-ID. ZUNDOKO-KIYOSHI.
000030 ENVIRONMENT DIVISION.
000040 DATA DIVISION.
000050 WORKING-STORAGE SECTION.
000060 77 END-FLAG                    PIC 9(01).
000070 77 WRK                         PIC 9(01).
000080 77 ZUN-COUNT                   PIC 9(01).
000090 77 SEED                        PIC 9(06).
000100 01 CURRENT-DATE-STRUCT.
000110   05 CURRENT-DATE.
000120     10 CURRENT-YEAR            PIC 9(04).
000130     10 CURRENT-MONTH           PIC 9(02).
000140     10 CURRENT-DAY             PIC 9(02).
000150   05 CURRENT-TIME.
000160     10 CURRENT-HOURS           PIC 9(02).
000170     10 CURRENT-MINUTE          PIC 9(02).
000180     10 CURRENT-SECOND          PIC 9(02).
000190     10 CURRENT-MILLISECONDS    COMP-2.
000200   05 DIFF-FROM-GMT             PIC S9(04).
000210 PROCEDURE DIVISION.
000220 MAIN SECTION.
000230* Initialize random seed
000240     MOVE FUNCTION CURRENT-DATE TO CURRENT-DATE-STRUCT.
000250     COMPUTE SEED = CURRENT-HOURS * 1000
000260       + CURRENT-MINUTE * 10 + CURRENT-SECOND.
000270     COMPUTE WRK = FUNCTION RANDOM(SEED).
000280* Zundoko
000290     PERFORM UNTIL END-FLAG = 1
000300       COMPUTE WRK = FUNCTION RANDOM * 10
000310       DIVIDE WRK BY 2 GIVING WRK REMAINDER WRK
000320       IF WRK = 1 THEN
000330         DISPLAY 'ズン'
000340         COMPUTE ZUN-COUNT = ZUN-COUNT + 1
000350       ELSE
000360         DISPLAY 'ドコ'
000370         IF ZUN-COUNT = 4 THEN
000380           MOVE 1 TO END-FLAG
000390         END-IF
000400         MOVE 0 TO ZUN-COUNT
000410       END-IF
000420     END-PERFORM.
000430     DISPLAY 'キ・ヨ・シ！'.
000440     STOP RUN.
```

COBOLなので、わかりやすさを意識して書いてみましたが、意外とわかりづらい？？？
そして、昔のことすぎて覚えてないので、COBOLっぽく書けてるのかは謎です。

## 簡単にCOBOLの説明

検索すればいくらでも出てくると思うので、さらっとだけ、COBOLのソースコードの書き方の説明をしておきます。COBOL85とかいろいろありますが、あんまり細かいことには興味ないと思いますので、とりあえずざっくり説明します！

### カラム(行頭からの文字の打つ場所)に意味がある！

Pythonか！っていうのよりももっと意味があります。

* 1～6カラム目
行番号とかを書きます。
書かなくても良いのですが、番号付いていた方がやっぱりわかりやすいですし、そもそもCOBOLの時代は机上コーディングと言って、コーディングシートという「紙」に鉛筆でプログラムを書き、机上デバッグという、いまでいうソースコードレビューみたいなことを行い、プログラムをコンピュータに打ち込む前にすでにデバッグをしておくということを行っていたため、行番号は人とお話をする上でとっても重要だったのですたぶん。コンピュータの利用料も、いまのIaaSなどのクラウドのように、使った分だけ請求されるみたいなシステムだったので、なるべくCPUを使わずに済むようなものを、実行前にわかっておく必要がありました。同じ従量課金でも、やってみてから考えるいまのクラウドとは真逆の発想ですね！

* 7カラム目
なんと、ここに「*」を書くとコメント行になります！ほかにもありますが、省略。

* 8～11カラム目
A領域と呼ばれる部分で、見出しとか、下の方に書いてある、4つのDIVISIONとかを書きます。

* 12～72カラム目
B領域呼ばれる部分で、いわゆる命令文とかのプログラムとかをここに書きます。

* 73～80カラム目
ここに書いたのはコメントとみなされ、めっちゃわかりやすい！

### 4つのDIVISION

なんか、かっこよくないですか？

COBOLでは、以下の4つのDIVISIONを定義し、その中に各意味通りの内容を書かないといけません！わかりやすい〜〜〜

* IDENTIFICATION DIVISION.
プログラムの名前とかを記述します

* ENVIRONMENT DIVISION.
ファイルとか、どんな塩梅で動かすのかとかを記述します

* DATA DIVISION.
変数定義みたいなことをします。構造体・共用体っぽく書きます

* PROCEDURE DIVISION.
まさに処理を書きます！

# 実行
```shell-session
$ cobc -x ./zd.cob ; ./zd
ズン
ズン
ズン
ズン
ズン
ドコ
ドコ
ズン
ドコ
ズン
ズン
ドコ
ズン
ズン
ドコ
ズン
ズン
ズン
ズン
ドコ
キ・ヨ・シ！
$
```
っぽくなりました！

# まとめ

こんな感じで、これからも弊社社員がどんどんブログを書いてくれるはずです。新卒未経験からのエンジニアになるくだりとか、社内ジョブチェンジでエンジニアに社内転職する方々の日常とか、そんなのも結構出てくると思いますので、応援よろしくお願いいたします！

以上
