= Security hardening on Ubuntu Server 14.04
:hp-tags: ubuntu

Recently I've been involved with a project where I needed to perform some security hardening on instances running Ubuntu Server 12.04, so I used this excellent guide as a starting point, then I added, removed and modified things as needed.

Assume that all these operations need to be performed as root, which you can either do with *sudo* or by logging in as root first. (I've noticed that Ubuntu users seem particularly averse to logging in as root, apparently preferring instead to issue an endless series of commands starting with sudo, but I'm afraid that kind of extra hassle is not for me, so I just log in as root first.)

== Harden SSH

 
I generally regard it as a very sensible idea to disable any kind of root login over SSH, so in */etc/ssh/sshd_config* change *PermitRootLogin* to *no*.

If SSH on your servers is open to the world then I also advise running SSH on a non-standard port in order to avoid incoming SSH hacking attempts. To do that, in */etc/ssh/sshd_config* change Port from *22* to another port of your choice, e.g. *1022*. Note that you'll need to update your firewall or EC2 security rules accordingly.

After making changes to SSH, reload the OpenSSH server:

[source,bash]
----
service ssh reload
----


=== Limit su access to administrators only

It generally seems like a sensible idea to make sure that only users in the sudo group are able to run the su command in order to act as (or become) root:


[source,bash]
----
dpkg-statoverride --update --add root sudo 4750 /bin/su
----


