= Security hardening on Ubuntu Server 14.04
:hp-tags: ubuntu

Recently I've been involved with a project where I needed to perform some security hardening on instances running Ubuntu Server 12.04, so I used this excellent guide as a starting point, then I added, removed and modified things as needed.

Assume that all these operations need to be performed as root, which you can either do with *sudo* or by logging in as root first. (I've noticed that Ubuntu users seem particularly averse to logging in as root, apparently preferring instead to issue an endless series of commands starting with sudo, but I'm afraid that kind of extra hassle is not for me, so I just log in as root first.)

== Harden SSH

 
I generally regard it as a very sensible idea to disable any kind of root login over SSH, so in */etc/ssh/sshd_config* change *PermitRootLogin* to *no*.

If SSH on your servers is open to the world then I also advise running SSH on a non-standard port in order to avoid incoming SSH hacking attempts. To do that, in */etc/ssh/sshd_config* change Port from *22* to another port of your choice, e.g. *1022*. Note that you'll need to update your firewall or EC2 security rules accordingly.

After making changes to SSH, reload the OpenSSH server:

[source,bash]
----
service ssh reload
----


=== Limit su access to administrators only

It generally seems like a sensible idea to make sure that only users in the sudo group are able to run the su command in order to act as (or become) root:


[source,bash]
----
dpkg-statoverride --update --add root sudo 4750 /bin/su
----


== Improve IP security

Add the following lines to /etc/sysctl.d/10-network-security.conf to improve IP security:

[source,bash]
----
# Ignore ICMP broadcast requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Disable source packet routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0 
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Ignore send redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Block SYN attacks
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Log Martians
net.ipv4.conf.all.log_martians = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0 
net.ipv6.conf.default.accept_redirects = 0

# Ignore Directed pings
net.ipv4.icmp_echo_ignore_all = 1
----

Load the new rules:

[source,bash]
----
----


== PHP hardening

If you're using PHP, these are changes worth making in /etc/php5/apache2/php.ini in order to improve the security of PHP:


. Add exec, system, shell_exec, and passthru to disable_functions.
. Change expose_php to Off.
. Ensure that display_errors, track_errors and html_errors are set to Off.


