= 0から始めるC言語 第一回 ~なぜ「プログラミングは難しい」と考えてしまうのか~
:hp-alt-title: starting-c-01
:hp-tags: magazine,cl0
:published_at: 2016-03-24

今回から(多分)プログラミング初心者目線で解りやすくC言語を教える新企画「0から始めるC言語」を書いていくのでよろしくお願いします。

== プログラミングを始めたい貴方へ

第一回は、「何故プログラミング初心者はプログラミング自体を怖がるのか」について考えていきたいと思います。根本的な問題が解決しなければしょうがないですからね。

さて貴方はC言語(プログラミング言語)を覚えたいですよね、この記事を開いたということは。しかし、以下の理由から結局諦めてしまっているもったいない人をいくつか見掛けることがよくあります。

- 文法が覚えられない
- 数学が苦手
- 何から手を付ければいいのかが分らない

多分どれかには引っかかると思います。さて、この連載では「文系でも理解出来る説明をする」ことを目標にて説明していくつもりなので安心してご覧ください。

== 結局「プログラム」って何？

プログラミングの初心者や未経験者からしたらlink:https://github.com[GitHub]やlink:https://qiita.com[Qiita]で公開されるような「プログラム」がよく理解出来ないなんてことも多いのではないかと思います。そのため、結局パソコン等で使う「プログラム」とは何かを説明したいと思います。

個人的な解釈で言ってしまえば、プログラムは「パソコンの為のToDo(やることリスト)」です。要は、ここにやってほしいことを書けばパソコンは素直に実行してくれるのです。そのため、パソコンにやってほしいことを伝えることが出来ればあなたは立派なプログラマーなのです。

と、いっても初心者はここで難しいことを考えてしまうからいけないのです。さっきも言った通り、やってほしいことをまとめることが出来れば良いのですから。もちろん日本語でもかまいませんし英語でも構いません。あなたの使いやすい言語で書けば良いのです。文法なんてすぐに覚える必要は全くありません。

これで少しは気が楽になったのではないでしょうか？プログラミングは「覚えよう」と思って勉強すると難しく感じますが、「慣れよう」と思って勉強すると案外スラスラ覚えられるものです。

次回はC言語について少しだけ解説したいなと思います。質問や感想は下のコメントフォームからお願いします。

== 「0から始めるC言語」について

この記事が気にいったなら他の記事もお勧めしています。link:http://tomewelcome.github.io/tag/cl0/[こちら]も是非ご覧ください。