= Secondary School
:published_at: 2017-02-05 15:25



Catford Boys had classes Named "A" though to "H" with "H" being the class with the pupils they had written of from day one and so made no attempt to educate, which is why when I left school in 1977 at sixteen I could still not read or write.

I enjoyed technical drawing and art at school, but only when I was in the mood to do.

Many a time I would just sit in the art class just staring of into space. Enjoying the world in my mind as I had no need for the so called real world (External world).

I spent a lot of time crying at school as I was forced to interact with a world I had no interest in.

In the early days of being in secondary school I enjoyed the music and history lessons but that change when the teachers teaching us change.
The music teacher had this trick of if he got call away from the classroom he would leave his glasses on his desk and when he came back he would put them back on and scan the class and then point out any pupil(s) that had left their desk or misbehaved in some other way of cause he must have been peeping though the window but it worked as he always got the right pupil(s) and after a couple of times no pupil would misbehave while he was out of the classroom.

The history teacher we first had was way ahead of his time in that he use cartoons and speech bubbles on the blackboard to help him teach us.

We first learnt about boats and this lead on to the discover of other countries and peoples which then lead on to other things. It was a great way to teach starting out with something invented by man and then showing how its creation effected history. I thing after the boat he went back in time to the wheel and we followed the effect it had on history. After 2 year we got a different history teacher I don't how much he knew about history but sure didn't know how to teach it.

He was the head teacher of the 4th year and was more interested in fulfilling his life ambition of caning ever pupil in the school and everyday after assembly he would have a long list of pupils to call out to go to his office to receive the cane.

When my turn came I asked him why I was receiving the cane as how would I know what I should not do again unless I knew the reason why. He was unable to give a reason and I asked how can he cane a pupil if he doesn't know what for and that he must have a reason as he had got to put into a book the reason why a pupil was to be caned. He backed down in the end but said if I told anybody then he would cane me.

He was not the only teacher who was into abusing pupils the fencing master use to punish a pupil by striking them across the stomach with his sabre. I only discovered that fact after I join his fencing class.

A few years after I left the school I heard he final got the sack after he cut a pupil, but he should have got more then just the sack he should have been changed with physical abuse of a minor.

= Sports Day

image::https://upload.wikimedia.org/wikipedia/commons/1/14/Fencing_foil_valid_surfaces_2009.svg[]

Fridays was sports day and every pupil had to do a sport of some sort.

I chose fencing and was quite good at it, but without asking me I was put in to fence for the school which I was very upset about, but my mum made me go and came to watch. So one of my Saturdays was wasted going to school to fence.

The first round was done in the main hall and so I had to put on a good show, but I felt I had done enough to not go though to the next round and so went and got changed, so was very upset when over the PA came the list of fencers that had gone though to the next round and my name was among them.

Thankfully the second round I fenced in was done in a classroom and so I was able to insure I never got though.

On the Monday I asked to change from fencing to swimming.

When I first switched to swimming I did go, but soon got bored with it, I've never enjoyed swimming in a pool but I do enjoy swimming in the sea.

So I soon stopped taking my swimming things and so got to sit in a classroom with the other pupils that had not brought their sports stuff and so could do their home work, but as I never had home work because of being in class &quot;H&quot; I could spend the time in my own world. So Fridays during the sports hour was the best times I had at school.