= Family holidays
:published_at: 2017-02-06 16:10

Family holidays were spent at Wallasey, Merseyside where we stayed with my mum's Sister and her (sister's) second husband in Trafalgar Road.

I would think we were the only faimly to use the coastline of the River Mersey as a beach and even paddled and swam in it despite the patches of oil on the beach at the time we were there (1970s).

My Brothers, sisters and cousins use to go swimming at the Guinea Gap Baths, I can only recall going once to swim, but may have gone more times but I prefer to swim in the sea or a river then at the swimming baths, so I tended to go and so called watch my family swim (it gave me time to be in my own world).

I hated the journey from Catford to Wallasey and would role myself up into the fetal position for large parts of the journey. To this day I don't like going on trips (A feeling of great sadness comes over me). I think it's due to my ASD and/or social anxiety disorder and leaving the know for the unknown, but must be more to it as the feeling is sadness and not fear. Coming back home which should have made me happy was hard and I would not only role up into a ball but cry as well, but that was because I was leaving behind the only person I have ever truly cared about and sadly we would break each others hearts over the years (13 April 1994 was to be the last day we would spend together and now I only see her in my dreams).