= ... why I bake bread

:hp-tags: bread

== background

About 10 years ago, or so, my daughter needed to avoid certain foods for 6 months. One of the foods was wheat. To make it easier to do, I started to bake spelt bread trying to aproximate toast.

This worked well.

* The daughter liked her father baking break for her, and it tasted good
* I discovered that I liked baking bread
** A reasonably fast result for your labour
** Not a huge investment in time
** A limited number of variables to tweak, a nearly unlimited amount of outcomes

Then, the six months were over.

image::https://lh3.googleusercontent.com/mU61owaXNKYQxJTuEMfloijeHeViqvTwSOYgl5MYTqczMn2in-QIqYVjiX3FoQKgse0HqdmUjEnffZktxVa8givjkJ6l2aJ_lyQ4eyhei0uwhfzJHQNjbIq9cDyjtrHnEAgWfVdo1N_DTzLKLWCmiafJhHM-CNql86LxghJiF1B0m9Kq4yVA1omsYOVR_0SvvqH13idifKSq-T0r7wWNbnbo3pTGYfgDgPAtz6YmKhJhn0oBvdm-8XCIRA9ELil-0oUITcTn-ZgiLr-_x3OHBe1I__5n7HNmkq68URVnnOJMGx0lyo6v9r8m_7GDkWs4j3F1Y7XBMP8_syf_JoT2HrCBDteXG18ns52kJRBVpfGudd1vN0FNB-DwCXGb8A8SPPqVyOSUe2QYqPGpXSTLlMXpaTdTZ9ikoeU0khddNkXURSSR80uOTIgITlS05vqOAbdf6lWI3YkUBGo3x74QKyKdg5drzGvcQ_zwnVXGcDgeZnXknHI8V_6QE3tSXps7gKUzviML8clOfmSZYGA6_maQa16J6HQ1N5V8_PmbMAy6V8O4E-hjORw8eJojuABPUJh6J4-fsZATpFWJXAnt1oddVJS-GuOzuoWdQwjhV6jWYfj_CRHuSQ=w1367-h1021-no[spelt bread]

== ever onwards

There I was, with a severe baking habit, needing a new outlet.

I started reading about baking and the beginnings of a "philosophy" developed.

I wanted to bake a bread that any family footnote:[in the Rhineland] within the last 1000 years could have baked.

To me that meant:
* Sourdough as a starter
* Spelt and rye footnote:[wheat came later]
* hand kneading
* large loafs (ca. 3kg)

Let's take them in turns.

=== sourdough

Sourdough speaks to my nerdy, geeky side, but in a good way. Making sourdough is easy. Basically you mix flour and water. Starting from there, there is a lot of ways to add complexity, leading up to arduino or raspberry pi controlled climate chambers for the dough.

But, as I was going into the direction of home baked bread, as it could have been done a 1000 years ago, an arduino was out of the question. I needed something more robust. footnote:[My job requires me leaving home on a monday morning, returning on a friday afternoon] So my sourdough starter lived in the fridge over the week, was "woken" with feedings friday night, saturday morning and saturday evening.

=== flour

Clearly 1000 years ago they would have had no white flour as today, but something shifted much more into the direction of wholemeal flour. I mixed spelt type 1050 and rye type 1150 flour for a good mix of authenticity and modern taste.

=== hand kneading

Of course

=== large loafs

A large loaf does not need that much more work, but keeps much better. In my experience, if stored outside the fridge, easily one to two weeks.

== original process

* wake up sourdough starter friday evening with 3 feedings
* mix flour with part of the water on saturday morning (sponge)
* mix sponge with sourdough starter, salt and the balance of water
* after an hour knead for 15 to 20 minutes
* after proofing form the loaf
* wait until loaf has proofed and put into oven

image::https://lh3.googleusercontent.com/YyqSmeTdwEW_ZC0tF2EnGyMvR2khkLWTbwN-tyFyXgVzUaOV4zQ8Qyg-p5KobO-5OObdNdGfANIgv7xqWQC87-D5ft1fh72bz4vZ4CwjQnSh1B3_IHkQ67XZzt4DPCFYry5Ovv4TrZNfi5VhcRNULLy9AWnV-hVFmMmDggsrggh7kvscHROpHASdM0p8QQ6UQ2O6gaS-AOij08fVsVjshNMr7DgJM3zb5hCj5AjZABeW7zPN037t6UBfmf1yw-KlyTFqK4Yn53FOm7hcKXge_xGDsJ-0gpEGoPaAeT91sMj4ddrxfppp3Rhkz2qFs4Hlk1OwH7L2_mggeGqEl1IvlZlYLxQ8EFq6n5_jaGQ-bQ9I3zGIcWYBU4WkXf0u5vWM4N9gDdYBBrcv8XTsAUz7jSTuq11Fg-Cd76Go-V6uJqfrwGRraf3uLxaGkFfTXXud0ci89vGyvWWokCuo824TQQ7gCm31gBUpcCKwS5_P0NgCPszlMYONBgL7KPsFaks_KAyyjZfcYS5QOo__IkVIDrxnSqNyepkj4S4K6n6eRZ9Ledv7ehfla4jCRXC-0yft6KXzptj5CRRBI-hrFVp4YhGwIXyXSRa3gcj11HexTToKJqU0ql3phg=w1020-h1021-no[spelt-rye sourdough bread]

== what hapened in the oven?

Fairly early in my baking career I found the several articles and books extolling the uses of a dutch oven footnote:[a name which strikes me, as a Rhinelander, as fairly funny] in baking bread. So, I use a dutch oven, on a baking stone, in an oven pre-heated to the max.

== who ate all that bread?

Once novelty wore off, mixed with different "phases" of the kids development through puberty, I went from a weekly to a bi-weekly bake. After about 2 years I had to stop the regular baking and so also the baking with sourdough.
