= Robcamstone
:published_at: 2017-02-05

== The Early Years

I use to enjoy singing and taking of Freddie Davies, but being so young have no memory of seeing him for the first time on Opportunity Knocks.

I enjoyed the laugher of my family including various uncles and aunts but when I got to around 5 or 6 years old I stopped talking and lost interest in interacting with others and the world around me. I could talk I just chose not to (selective mutism).

I disliked primary school and cried a lot, so much so that my father for the first year, was always being called in by the school to take me home (He was a Foreman Baker and so worked nights).

The only thing I learn by the time I left Plassy Road School, Rushey Green, Catford was that if you are different for any reason that's reason enough for others to judge and bully you. The year I left was the school's last year it closed at the end of that years' term.

== Saturday Morning Pictures
During the late 60s and the 70s must Saturday's were spent at Saturday Morning Pictures at the ABC Cinema in Catford.