= Part 1. Introducing SPAs

== Mi spa:

:hp-tags: test

https://txemis.github.io/spa/spa.html[spa]

{empty}


https://stackoverflow.com/questions/18327314/how-to-allow-http-content-within-an-iframe-on-a-https-site

<iframe src="/redirect.php?url=http://www.example.com/"></iframe>
<iframe src="spa/spa.html?url=https://txemis.github.io/"></iframe>
<iframe src="spa/spa.html?url=//txemis.github.io/"></iframe>
<iframe src="about/index.html?url=//txemis.github.io/"></iframe>
<iframe src="index.html?url=//txemis.github.io/about"></iframe>

++++
<iframe src="index.html?url=//txemis.github.io/about"></iframe>
++++



++++
<iframe  style="border: 0; width: 350px; height: 470px;" src="index.html?url=//txemis.github.io/about"></iframe>

++++

{empty}

<iframe src="scrapedcontent.php"></iframe>

++++
<iframe src="about/index.html"></iframe>
++++




++++
<iframe style="border: 0; width: 350px; height: 470px;" src="//bandcamp.com/EmbeddedPlayer/album=2869458964/size=large/bgcol=333333/linkcol=0f91ff/tracklist=false/transparent=true/" seamless><a href="http://mocamborecords.bandcamp.com/album/showdown">SHOWDOWN by THE MIGHTY MOCAMBOS</a></iframe>
++++

{empty}


++++
<iframe style="border: 1; width: 350px; height: 470px </iframe>

++++

++++

<html>
<body>
<iframe width="200" height="100" scrolling="no" frameborder="no" >

<!doctype html>
<html>
<head>
  <title>SPA Chapter 1 section 1.2.5</title>
  <style type="text/css">
    body {
      width    : 100%;
      height   : 100%;
      overflow : hidden;
      background-color : #777;
    }

    #spa {
      position : absolute;
      top      : 8px;
      left     : 8px;
      bottom   : 8px;
      right    : 8px;
      border-radius    : 8px 8px 0 8px;
      background-color : #fff;
    }

    .spa-slider {
      position : absolute;
      bottom   : 0;
      right    : 2px;
      width    : 300px;
      height   : 16px;
      cursor   : pointer;
      border-radius    : 8px 0 0 0;
      background-color : #f00;
    }
  </style>

  <script type="text/javascript" src=
    "http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">
  </script>
  
  <script type="text/javascript">
  /*jslint         browser : true, continue : true,
    devel  : true, indent  : 2,    maxerr   : 50,
    newcap : true, nomen   : true, plusplus : true,
    regexp : true, sloppy  : true, vars     : true,
    white  : true
  */
  /*global jQuery */

  // Module /spa/
  // Provides chat slider capability
  //
  var spa = (function ( $ ) {
    // Module scope variables
    var
      // Set constants
      configMap = {
        extended_height  : 434,
        extended_title   : 'Click to retract',
        retracted_height : 16,
        retracted_title  : 'Click to extend',
        template_html    : '<div class="spa-slider"><\/div>'
      },
      
      // Declare all other module scope variables
      $chatSlider,
      toggleSlider, onClickSlider, initModule;

    // DOM method /toggleSlider/
    // alternates slider height
    //
    toggleSlider = function () {
      var
        slider_height = $chatSlider.height();

      // extend slider if fully retracted
      if ( slider_height === configMap.retracted_height ) {
        $chatSlider
          .animate({ height : configMap.extended_height })
          .attr( 'title', configMap.extended_title );
        return true;
      }

      // retract slider if fully extended
      else if ( slider_height === configMap.extended_height ) {
        $chatSlider
          .animate({ height : configMap.retracted_height })
          .attr( 'title', configMap.retracted_title );
        return true;
      }
      // do not take action if slider is in transition
      return false;
    };

    // Event handler /onClickSlider/
    // receives click event and calls toggleSlider
    //
    onClickSlider = function ( event ) {
      toggleSlider();
      return false;
    };

    // Public method /initModule/
    // sets initial state and provides feature
    //
    initModule = function ( $container ) {
    
      // render HTML
      $container.html( configMap.template_html );
      $chatSlider = $container.find( '.spa-slider' );

      // initialize slider height and title
      // bind the user click event to the event handler
      $chatSlider
        .attr( 'title', configMap.retracted_title )
        .click( onClickSlider );

      return true;
    };

    return { initModule : initModule };

  }( jQuery ));

  // Start spa once DOM is ready
  //
  jQuery(document).ready(
    function () { spa.initModule( jQuery('#spa') ); } 
  );
  </script>
</head>

<body>
  <div id="spa"></div>
</body>
</html>


</iframe>
</html>
</body>

++++


---