
export default {
  AppStates: {
    INIT: 'INIT',
    SYNCHRONIZE: 'SYNCHRONIZE',
    READY: 'READY'
  },

  ActionTypes: {
    INITIALIZE: 'INITIALIZE',
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
    RECEIVE_INIT: 'RECEIVE_INIT',
    START_SYNCHRONIZE: 'START_SYNCHRONIZE',
    FINISH_SYNCHRONIZE: 'FINISH_SYNCHRONIZE',
    PUBLISH_POST: 'PUBLISH_POST',
    UNPUBLISH_POST: 'UNPUBLISH_POST',
    LOCALSAVE_POST: 'LOCALSAVE_POST',
    REMOTESAVE_POST: 'REMOTESAVE_POST',
    GET_POST: 'GET_POST',
    GET_POSTS: 'GET_POSTS',
    RECEIVE_POST: 'RECEIVE_POST',
    RECEIVE_POSTS: 'RECEIVE_POSTS',
    RECEIVE_REMOTESAVE: 'RECEIVE_REMOTESAVE',
    RECEIVE_PUBLISH: 'RECEIVE_PUBLISH',
    RECEIVE_UNPUBLISH: 'RECEIVE_UNPUBLISH',
    RECEIVE_AUTHENTICATION: 'RECEIVE_AUTHENTICATION',
    SAVEANDPUBLISH_SETTINGS: 'SAVEANDPUBLISH_SETTINGS',
    RECEIVE_SETTINGS: 'RECEIVE_SETTINGS'
  },

  PayloadSources: {
    VIEW_ACTION: 'VIEW_ACTION' ,
  }

};
